baseURL = "https://broadcaststorm.io"
languageCode = "en-us"
title = "BroadcastStorm.io"
theme = "hugo-theme-shell"

[Params]
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "BroadcastStorm.io"
  [Params.Terminal]
  # Note: color schema
  # Note: You can choose between
  # Note: ["monokai", "powershell", "gruvbox_light", "gruvbox_dark", "solarized_light", "solarized_dark", "ubuntu", "retro"]
  schema = "ubuntu"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "broadcast"
  pcName = "storm"
  workDir = "topkek"
  profile = "bs.txt"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  terminalDelay = 12

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  activityDelay = 5

  description = """
  Broadcast Storm:
  The ultimate stand-in for "BS" in emails, IMs, meeting titles, and more!

  """

  # Note: If you want to use a Markdown file, you can use the following
  description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "my_junk"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [
    ["Beacons", "beacons.ai/loopednetwork"],
    ["Shitposting", "https://twitter.com/loopednetwork],
    ["Long Form Shitposting", "http://looped.network"],
    ["Bad Chess", "https://lichess.org/@/LaifuMoe"],
    ["Laifu", "https://laifu.moe"]
  ]
